"""
Clearly marked DEMO / SEED data based on real market patterns in Antwerp.
These are NOT live scraped listings. They serve for development and demonstration.
"""
from datetime import datetime, timedelta
import hashlib

DEMO_PROPERTIES = [
    {
        "source": "demo",
        "source_listing_id": "demo-001",
        "url": "https://example.com/demo/joannasteeg-6",
        "title": "Totaal te renoveren arbeiderswoning – Joannasteeg 6, 2060 Antwerpen",
        "price": 165000,
        "address": "Joannasteeg 6",
        "postal_code": "2060",
        "city": "Antwerpen",
        "district": "Antwerpen-Noord / Park Spoor Noord",
        "property_type": "huis",
        "living_area": 68,
        "bedrooms": 1,
        "bathrooms": 1,
        "year_built": 1875,
        "epc_label": "E",
        "epc_score": 457,
        "description": "Totaal te renoveren charmante arbeiderswoning in autoloze steeg, op een boogscheut van Park Spoor Noord. Dak reeds geïsoleerd. EPC E. Ideaal DIY-project in opkomende buurt.",
        "images": [],
        "is_to_renovate": True,
        "is_fully_to_renovate": True,
        "features": ["dak_geisoleerd", "charmante_elementen"],
    },
    {
        "source": "demo",
        "source_listing_id": "demo-002",
        "url": "https://example.com/demo/dijlestraat",
        "title": "Te renoveren huis met 6 slaapkamers – Dijlestraat, 2060 Antwerpen",
        "price": 239000,
        "address": "Dijlestraat",
        "postal_code": "2060",
        "city": "Antwerpen",
        "district": "Slachthuiswijk",
        "property_type": "huis",
        "living_area": 139,
        "bedrooms": 6,
        "bathrooms": 1,
        "year_built": 1920,
        "epc_label": "E",
        "epc_score": 448,
        "description": "Te renoveren woning met 6 slaapkamers in opkomende Slachthuiswijk. Veel volume, potentieel voor opsplitsing of studentenverhuur. Renovatieplicht aanwezig.",
        "images": [],
        "is_to_renovate": True,
        "is_fully_to_renovate": True,
        "is_investment": True,
        "features": ["veel_volume", "opkomende_wijk"],
    },
    {
        "source": "demo",
        "source_listing_id": "demo-003",
        "url": "https://example.com/demo/magdalenastraat",
        "title": "Te renoveren gezinswoning – Magdalenastraat, 2018 Zurenborg",
        "price": 320000,
        "address": "Magdalenastraat",
        "postal_code": "2018",
        "city": "Antwerpen",
        "district": "Zurenborg",
        "property_type": "huis",
        "living_area": 181,
        "bedrooms": 4,
        "bathrooms": 2,
        "year_built": 1910,
        "epc_label": "F",
        "epc_score": 520,
        "description": "Te renoveren gezinswoning in de gegeerde Zurenborgwijk, dicht bij Dageraadplaats. Ruime volumes, goede locatie, duidelijk renovatiepotentieel.",
        "images": [],
        "is_to_renovate": True,
        "is_fully_to_renovate": True,
        "features": ["zurenborg", "ruime_volumes"],
    },
    {
        "source": "demo",
        "source_listing_id": "demo-004",
        "url": "https://example.com/demo/vandenpeereboomstraat",
        "title": "5-slaapkamer woning met studio – Vandenpeereboomstraat 70, 2140",
        "price": 275000,
        "address": "Vandenpeereboomstraat 70",
        "postal_code": "2140",
        "city": "Antwerpen",
        "district": "Borgerhout / grens Zurenborg",
        "property_type": "huis",
        "living_area": 200,
        "bedrooms": 5,
        "bathrooms": 2,
        "year_built": 1910,
        "epc_label": "E",
        "epc_score": 410,
        "description": "Te renoveren woning met 5 slaapkamers en reeds (deels) gerenoveerde studio. Uitstekende ligging op de grens van Zurenborg. Sterk potentieel voor opsplitsing.",
        "images": [],
        "is_to_renovate": True,
        "is_investment": True,
        "features": ["studio", "zurenborg_grens"],
    },
    {
        "source": "demo",
        "source_listing_id": "demo-005",
        "url": "https://example.com/demo/kapelsesteenweg",
        "title": "Te renoveren huis – Kapelsesteenweg 135, 2180 Ekeren",
        "price": 189000,
        "address": "Kapelsesteenweg 135",
        "postal_code": "2180",
        "city": "Antwerpen",
        "district": "Ekeren",
        "property_type": "huis",
        "living_area": 120,
        "bedrooms": 3,
        "bathrooms": 1,
        "year_built": 1955,
        "epc_label": "F",
        "epc_score": 580,
        "description": "Te renoveren woning in Ekeren. Scherpe prijs, relatief rustige omgeving, geschikt voor grondige DIY-renovatie.",
        "images": [],
        "is_to_renovate": True,
        "is_fully_to_renovate": True,
        "features": [],
    },
]


def content_hash(data: dict) -> str:
    raw = f"{data.get('price')}|{data.get('living_area')}|{data.get('epc_label')}|{data.get('description','')[:200]}"
    return hashlib.sha256(raw.encode()).hexdigest()[:16]
